# Copyright 2022 liam
# See LICENSE file for licensing details.
#

options:
  os-public-hostname:
    default: ovn-relay.juju
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the neutron image provider.
    type: string
